### ISSUE TITLE
Delivery Feedback

### ISSUE THREAD

**Issue by vilunov** [bul-nick-al/scalaToDo#1]
1. Инициализация проекта через наследование разных трейтов – это так называемый "cake pattern", который уже давно называется "cake antipattern".
2. Нужно нормально завершать прилу с завершением актор-системы.
3. тесты
4. ридми
5. Глобальный контекст к БД. Делай `TasksQuill` не объектом.
6. Лучше юзать асинхронный коннектор к БД.
7. Не нужно всё держать в одном месте, разбей `TasksQuill` на модуль для управления юзерами и тасками например.

**Comment by vilunov** [comment]
5. Делай его классом, который принимает в себя всю необходимую конфигурацию, и создавай инстанс этого класс в мейне, потом прокидывай его во все модули, которые пользуются квиллом.

**Comment by vilunov** [comment]
8. Ещё не увидел, у тебя все пекеджи проекта лежат в дефолтном пекедже, помести их в какой-нибудь общий пекедж, например `todo`, `api` станет `todo.api`

**Comment by vilunov** [comment]
1. Бтв кейк лучше тоже переделать на классы, которые независимо инстанциируются в мейне

**Comment by bul-nick-al** [comment]
Все сделал
